// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using appserverproject.Data;

#nullable disable

namespace appserverproject.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20230404064217_FirstMigrations")]
    partial class FirstMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("appserverproject.Data.Promo", b =>
                {
                    b.Property<int>("PromoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PromoCurrency")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PromoEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PromoStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromoTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PromoType")
                        .HasColumnType("INTEGER");

                    b.HasKey("PromoId");

                    b.ToTable("Promos");

                    b.HasData(
                        new
                        {
                            PromoId = 1,
                            Channel = "",
                            Model = "",
                            PromoCurrency = 1,
                            PromoEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PromoStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PromoTitle = "Promo 1",
                            PromoType = 1
                        },
                        new
                        {
                            PromoId = 2,
                            Channel = "",
                            Model = "",
                            PromoCurrency = 1,
                            PromoEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PromoStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PromoTitle = "Promo 2",
                            PromoType = 1
                        },
                        new
                        {
                            PromoId = 3,
                            Channel = "",
                            Model = "",
                            PromoCurrency = 1,
                            PromoEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PromoStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PromoTitle = "Promo 3",
                            PromoType = 1
                        },
                        new
                        {
                            PromoId = 4,
                            Channel = "",
                            Model = "",
                            PromoCurrency = 1,
                            PromoEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PromoStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PromoTitle = "Promo 4",
                            PromoType = 1
                        },
                        new
                        {
                            PromoId = 5,
                            Channel = "",
                            Model = "",
                            PromoCurrency = 1,
                            PromoEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PromoStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PromoTitle = "Promo 5",
                            PromoType = 1
                        },
                        new
                        {
                            PromoId = 6,
                            Channel = "",
                            Model = "",
                            PromoCurrency = 1,
                            PromoEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PromoStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PromoTitle = "Promo 6",
                            PromoType = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
